### ISSUE TITLE
Návrh a popis používateľského rozhrania

### ISSUE THREAD

**Issue by chovanec51** [TIS2020-FMFI/uml-3d#14]

**Comment by miriss212** [comment]
Začínam pracovať na návrhu nových komponentov rozhrania a popise toho čo už model obsahuje.

**Comment by miriss212** [comment]
https://docs.google.com/document/d/1PMuTZ2GLqz_IYspPM6EaCrZgqX5SqzMgm2jiSTN_ZJo/edit?usp=sharing

**Comment by pavelpetrovic** [comment]
dakujem. su to uz vsetky okienka/dialogy, ktore bude aplikacia zobrazovat?
skontrolovali navrh aj ostatni clenovia timu? maju k nemu nejake pripomienky alebo namety?
ak oboje bude hotovo, tak potom si dohodnite stretnutie so zadavatelom, kde to s nim podrobne prediskutujete, prosim.

**Comment by miriss212** [comment]
https://docs.google.com/document/d/1PMuTZ2GLqz_IYspPM6EaCrZgqX5SqzMgm2jiSTN_ZJo/edit?usp=sharing
Dokončila som návrh grafického rozhrania. 
Pozrite si to mladí muži prosím vás. Ďakujem.

**Comment by chovanec51** [comment]
Navrh som si precital, vsetko je tak ako bolo dohodnute, dobra praca

**Comment by miriss212** [comment]
Po pripomienke od p.Petroviča som pridala grafické znázornenie druhej požiadavky. Pridanie tlačidla a vybielenie okienka.
