### ISSUE TITLE
Stretnutie s cvičiacim (pán P. Petrovič)

### ISSUE THREAD

**Issue by chovanec51** [TIS2020-FMFI/uml-3d#3]

**Comment by pavelpetrovic** [comment]
píšem si do kalendára štvrtok 19h ak so dobre pochopil.

**Comment by chovanec51** [comment]
Ano, na stretnutiach s p. Polasikom sme sa dohodli v stvrtky o 19:00.

so 3. 10. 2020 o 11:17 Pavel Petrovič <notifications@github.com> napísal(a):

**Comment by pavelpetrovic** [comment]
aha takto. su dve moznosti: bud vystacime s jednym stretnutim, kde by som bol pritomny aj ja, alebo budeme mat jedno nase stretnutie ohladne pokroku na ulohach na projekte a zaroven jedno s Ivanom Polaskom ohladne konzultacii k samotnym technologiam a obsahu, kedze mate trochu technologicky narocnejsi projekt. dohodnem sa s nim, co mu lepsie vyhovuje a dame vediet.
