### ISSUE TITLE
Inštalácia Enterprise Architect a Unity

### ISSUE THREAD

**Issue by chovanec51** [TIS2020-FMFI/uml-3d#5]
Nainštalovať si dané programy do 6.10.

**Comment by miriss212** [comment]
Podarilo sa mi nainštalovať obidva

**Comment by chovanec51** [comment]
nainštaloval som oba programy

**Comment by FedorMatFyz** [comment]
Hotovo

**Comment by marekdurana** [comment]
Unity nainštalované, EA na mac som inštaloval cez Wine (prostredie je len pre windows), no nedarí sa to rozbehnúť zatiaľ
