### ISSUE TITLE
Katalóg požiadaviek

### ISSUE THREAD

**Issue by marekdurana** [TIS2020-FMFI/uml-3d#8]
Na základe komunikácie so zadávateľom projektu je vytváraný katalóg požiadaviek
beta verzia:
https://docs.google.com/document/d/1vubvz_woIDrUzL7Lo9RffMeD_1ZestcBtKhqGo-yI3c/edit?usp=sharing

**Comment by chovanec51** [comment]
Dopisal som kapitolu 1.2, 2.4 a cast z 1.3, 2.2, 2.3

**Comment by chovanec51** [comment]
doplnil som 2.2 a 2.3

**Comment by miriss212** [comment]
Pridala som skratky do kapitoly 1.3, kapitolu 2.1

**Comment by marekdurana** [comment]
Doplnil som kapitolu 3.1 a 1.1, opravil som diakritiku

**Comment by chovanec51** [comment]
@pavelpetrovic Prepísal som sa požiadavky a cakam na schvalenie

**Comment by marekdurana** [comment]
Doplnil som  obsah, konektivitu na zdroje a upravil finálnu štruktúru

**Comment by marekdurana** [comment]
zadávateľ schválil katalog, opravil som jeho námietky a nahral som ho do repozitára /prílohy

**Comment by pavelpetrovic** [comment]
prvych par komentarov
[katalog_poziadaviek_s_pripomienkami.docx](https://github.com/TIS2020-FMFI/uml-3d/files/5430048/katalog_poziadaviek_s_pripomienkami.docx)

**Comment by chovanec51** [comment]
@pavelpetrovic Upravil som katalog poziadaviek podla pripomienok.

**Comment by pavelpetrovic** [comment]
Ďakujem. Už sa to blíži. Môj základný problém s týmto textom je ten, že dokument má byť súhrn požiadaviek na výslednú aplikáciu. T.j. že niekto bude môcť urobiť niečo. Nemajú to byť požiadavky na vývojový tím. Napríklad:

"Rozšíriť implementáciu jazyka OAL..."   je požiadavka na vývojový tím. 
ale napr.
"Aplikácia umožní vývojárovi animácie vkladať skripty v rozšírenom jazyku OAL"
alebo
"Aplikácia umožní vývojárovi animácie v skripte zadefinovať metódy, ktoré sa skladajú z hlavičky metódy a tela metódy."

Ešte mi tam stále chýba veľa podrobností, podľa tohto by to predsa nikto nemal šancu naprogramovať...
Iba zopár konkrétnych som v dokumente aj vypichol.
Skúste to ešte trochu celé zlepšiť a potom to teda dajte svojmu zadávateľovi skontrolovať, okomentovať, a po prípadných vyžiadaných úpravách aj schváliť. Ďakujem.

**Comment by chovanec51** [comment]
Katalóg som znova upravil a prešiel som ho so zadávateľom. Zadávateľ ho schválil.

**Comment by miriss212** [comment]
Pridala som jednu požiadavky ohľadne druhej úlohy. Týkajúcu sa tlačidla, ktoré tam budeme pridávať.
